library SEAllDspModules;

{$I DAV_Compiler.inc}

uses
  SysUtils,
  Classes,
  DAV_SECommon,
  DAV_SEModule,
  SEApproximationsModule in '..\Approximations\SEApproximationsModule.pas',
  SEAudioFileOscillatorModule in '..\Audio File Oscillator\SEAudioFileOscillatorModule.pas',
  SEAudioRGBModule in '..\AudioRGB\SEAudioRGBModule.pas',
  SEBarberpoleModule in '..\Barberpole\SEBarberpoleModule.pas',
  SEBassEnhancerModule in '..\Bass Enhancer\SEBassEnhancerModule.pas',
  SEBufferedMp3PlayerModule in '..\MP3 Player\SEBufferedMp3PlayerModule.pas',
  SEButterworthModule in '..\Butterworth\SEButterworthModule.pas',
  SEButterworthSplitterModule in '..\Butterworth\SEButterworthSplitterModule.pas',
  SEChebyshev1FilterModule in '..\Chebyshev\SEChebyshev1FilterModule.pas',
  SEChebyshev2FilterModule in '..\Chebyshev\SEChebyshev2FilterModule.pas',
  SEChebyshevWaveshaperModule in '..\ChebyshevWaveshaper\SEChebyshevWaveshaperModule.pas',
  SEChorusModule in '..\Chorus\SEChorusModule.pas',
  SEConvolutionModule in '..\Convolution\SEConvolutionModule.pas',
  SEDitherHighshelfNoiseshaperModule in '..\Dither & NoiseShaper\SEDitherHighshelfNoiseshaperModule.pas',
  SEDitherNoiseshaperModule in '..\Dither & NoiseShaper\SEDitherNoiseshaperModule.pas',
  SEDitherSharpNoiseshaperModule in '..\Dither & NoiseShaper\SEDitherSharpNoiseshaperModule.pas',
  SEDynamicsModule in '..\Dynamics\SEDynamicsModule.pas',
  SEEnvelopeModule in '..\Envelope\SEEnvelopeModule.pas',
  SEExciterModule in '..\Exciter\SEExciterModule.pas',
  SEFiltersModule in '..\Filters\SEFiltersModule.pas',
  SEFrequencyShifterModule in '..\Frequency Shifter\SEFrequencyShifterModule.pas',
  SEHarmonicBassModule in '..\Bass Enhancer\SEHarmonicBassModule.pas',
  SELeslieModule in '..\Leslie\SELeslieModule.pas',
  SELightweightDynamicsModule in '..\Lightweight Dynamics\SELightweightDynamicsModule.pas',
  SELightweightFiltersModule in '..\Filters\SELightweightFiltersModule.pas',
  SELinkwitzRileyModule in '..\Linkwitz-Riley\SELinkwitzRileyModule.pas',
  SELowLatencyConvolutionModule in '..\Convolution\SELowLatencyConvolutionModule.pas',
  SEModDelayModule in '..\ModDelay\SEModDelayModule.pas',
  SEMp3PlayerModule in '..\MP3 Player\SEMp3PlayerModule.pas',
  SEPhaserModule in '..\Phaser\SEPhaserModule.pas',
  SEPitchShifterModule in '..\Pitch Shifter\SEPitchShifterModule.pas',
  SEPlateVerbModule in '..\Reverb\SEPlateVerbModule.pas',
  SERealverbModule in '..\Realverb\SERealverbModule.pas',
  SERealverbStereoModule in '..\Realverb\SERealverbStereoModule.pas',
  SEResurrectionBassModule in '..\Bass Enhancer\SEResurrectionBassModule.pas',
  SEReverbModule in '..\Reverb\SEReverbModule.pas',
  SESimpleAudioFileOscillatorModule in '..\Audio File Oscillator\SESimpleAudioFileOscillatorModule.pas',
  SESimpleMp3PlayerModule in '..\MP3 Player\SESimpleMp3PlayerModule.pas',
  SESimpleVocoderModule in '..\Vocoder\SESimpleVocoderModule.pas',
  SESineModule in '..\Sine\SESineModule.pas',
  SETanhAproximationsModule in '..\Tanh Aproximations\SETanhAproximationsModule.pas',
  SETransientProcessorModule in '..\Transient Processor\SETransientProcessorModule.pas',
  SETunerModule in '..\Tuner\SETunerModule.pas',
  SEVibratoModule in '..\Vibrato\SEVibratoModule.pas',
  SEVocoderModule in '..\Vocoder\SEVocoderModule.pas',
  SEVoiceSynthModule in '..\VoiceSynth\SEVoiceSynthModule.pas',
  SENoiseReductionModule in '..\Noise Reduction\SENoiseReductionModule.pas',
  SELookaheadLimiterModule in '..\Lookahead Limiter\SELookaheadLimiterModule.pas';

{$E sem}
{$R *.res}

type
  TSEModuleBaseClass = class of TSEModuleBase;

const
  CModuleClasses : array [0..199] of TSEModuleBaseClass = (
    TSEBassEnhancerModule,
    TSEResurrectionBassModule,
    TSEHarmonicBassModule,
    TSEFastSineApproximationsSingleModule,
    TSEFastSineApproximationsDoubleModule,
    TSEFastCosineApproximationsSingleModule,
    TSEFastCosineApproximationsDoubleModule,
    TSEFastTangensApproximationsSingleModule,
    TSEFastTangensApproximationsDoubleModule,
    TSEFastCotangensApproximationsSingleModule,
    TSEFastCotangensApproximationsDoubleModule,
    TSEFastArcTanApproximationsSingleModule,
    TSEFastArcTanApproximationsDoubleModule,
    TSEFastArcCotanApproximationsSingleModule,
    TSEFastArcCotanApproximationsDoubleModule,
    TSEFastLog2ApproximationsSingleModule,
    TSEFastLog2ApproximationsDoubleModule,
    TSEFastPower2ApproximationsSingleModule,
    TSEFastPower2ApproximationsDoubleModule,
    TSEAudioRGBModule,
    TSERGBToHSLModule,
    TSEHSLToRGBModule,
    TSEBarberpoleModule,
    TSEStaticButterworthLPModule,
    TSEStaticButterworthHPModule,
    TSEControlableButterworthLPModule,
    TSEControlableButterworthHPModule,
    TSEAutomatableButterworthLPModule,
    TSEAutomatableButterworthHPModule,
    TSEAutomatableXButterworthLPModule,
    TSEAutomatableXButterworthHPModule,
    TSEStaticButterworthSplitterModule,
    TSEControlableButterworthSplitterModule,
    TSEAutomatableButterworthSplitterModule,
    TSEStaticChebyshev1FilterLPModule,
    TSEStaticChebyshev1FilterHPModule,
    TSEControlableChebyshev1FilterLPModule,
    TSEControlableChebyshev1FilterHPModule,
    TSEAutomatebleChebyshev1FilterLPModule,
    TSEAutomatebleChebyshev1FilterHPModule,
    TSEAutomatebleXChebyshev1FilterLPModule,
    TSEAutomatebleXChebyshev1FilterHPModule,
    TSEStaticChebyshev2FilterLPModule,
    TSEStaticChebyshev2FilterHPModule,
    TSEControlableChebyshev2FilterLPModule,
    TSEControlableChebyshev2FilterHPModule,
    TSEAutomatebleChebyshev2FilterLPModule,
    TSEAutomatebleChebyshev2FilterHPModule,
    TSEAutomatebleXChebyshev2FilterLPModule,
    TSEAutomatebleXChebyshev2FilterHPModule,
    TSEStaticChebyshevWaveshaperModule,
    TSEControlableChebyshevWaveshaperModule,
    TSEAutomatableChebyshevWaveshaperModule,
    TSEChorusModule,
    TSEStkChorusModule,
    TSEConvolutionModule,
    TSELowLatencyConvolutionModule,
    TSimpleDirectGateStaticSEModule,
    TSimpleDirectGateParamStaticSEModule,
    TSimpleDirectGateAutomatableSEModule,
    TSoftDirectGateStaticSEModule,
    TSoftDirectGateParamStaticSEModule,
    TSoftDirectGateAutomatableSEModule,
    TBrickwallLimiterStaticSEModule,
    TBrickwallLimiterParamStaticSEModule,
    TBrickwallLimiterAutomatableSEModule,
    TBrickwallSoftLimiterStaticSEModule,
    TBrickwallSoftLimiterParamStaticSEModule,
    TBrickwallSoftLimiterAutomatableSEModule,
    TBrickwallSimpleSoftLimiterStaticSEModule,
    TBrickwallSimpleSoftLimiterParamStaticSEModule,
    TBrickwallSoftLimiterAutomatableSEModule,
    TClassicGateStaticSEModule,
    TClassicGateParamStaticSEModule,
    TClassicGateAutomatableSEModule,
    TSoftClassicGateStaticSEModule,
    TSoftClassicGateParamStaticSEModule,
    TSoftClassicGateAutomatableSEModule,
    TLimiterStaticSEModule,
    TLimiterParamStaticSEModule,
    TLimiterAutomatableSEModule,
    TSoftLimiterStaticSEModule,
    TSoftLimiterParamStaticSEModule,
    TSoftLimiterAutomatableSEModule,
    TSimpleSoftLimiterStaticSEModule,
    TSimpleSoftLimiterParamStaticSEModule,
    TSimpleSoftLimiterAutomatableSEModule,
    TRangeGateStaticSEModule,
    TRangeGateParamStaticSEModule,
    TRangeGateAutomatableSEModule,
    TSimpleCompressorStaticSEModule,
    TSimpleCompressorParamStaticSEModule,
    TSimpleCompressorAutomatableSEModule,
    TSoftKneeCompressorStaticSEModule,
    TSoftKneeCompressorParamStaticSEModule,
    TSoftKneeCompressorAutomatableSEModule,
    TRMSCompressorStaticSEModule,
    TRMSCompressorParamStaticSEModule,
    TRMSCompressorAutomatableSEModule,
    TSEEnvelopeModule,
    TSEHilbertModule,
    TSEBasicLowpassModule,
    TSEBasicHighpassModule,
    TSEBasicBandpassModule,
    TSEBasicNotchModule,
    TSEBasicLowshelfModule,
    TSEBasicLowshelfAModule,
    TSEBasicLowshelfBModule,
    TSEBasicHighshelfModule,
    TSEBasicHighshelfAModule,
    TSEBasicHighshelfBModule,
    TSEBasicPeakModule,
    TSEBasicAllpassModule,
    TSEBasicShapeModule,
    TSELightweightLowpassModule,
    TSELightweightHighpassModule,
    TSELightweightBandpassModule,
    TSELightweightNotchModule,
    TSELightweightLowshelfModule,
    TSELightweightLowshelfAModule,
    TSELightweightLowshelfBModule,
    TSELightweightHighshelfModule,
    TSELightweightHighshelfAModule,
    TSELightweightHighshelfBModule,
    TSELightweightPeakModule,
    TSELightweightAllpassModule,
    TSELightweightShapeModule,
    TLightweightCompressorStaticSEModule,
    TLightweightCompressorParamStaticSEModule,
    TLightweightCompressorAutomatableSEModule,
    TLightweightFeedbackCompressorStaticSEModule,
    TLightweightFeedbackCompressorParamStaticSEModule,
    TLightweightFeedbackCompressorAutomatableSEModule,
    TLightweightLimiterStaticSEModule,
    TLightweightLimiterParamStaticSEModule,
    TLightweightLimiterAutomatableSEModule,
    TLightweightGateStaticSEModule,
    TLightweightGateParamStaticSEModule,
    TLightweightGateAutomatableSEModule,
    TSELinkwitzRileyStaticModule,
    TSELinkwitzRileyControlableModule,
    TSELinkwitzRileyAutomatableModule,
    TSEPhaserStaticModule,
    TSEPhaserControllableModule,
    TSEStkPitchshifterModule,
    TSERealverbModule,
    TSERealverbStereoModule,
    TSEPlateReverbStaticModule,
    TSEPlateReverbControllableModule,
    TSEFreeverbStaticModule,
    TSEFreeverbControllableModule,
    TSEStkNReverbStaticModule,
    TSEStkNReverbControllableModule,
    TSEStkJCReverbStaticModule,
    TSEStkJCReverbControllableModule,
    TSEStkNReverb2StaticModule,
    TSEStkNReverb2ControllableModule,
    TSEStkJCReverb2StaticModule,
    TSEStkJCReverb2ControllableModule,
    TSESineModule,
    TSESineCosineModule,
    TSESine2Module,
    TSETanhAproximationsModule,
    TSETanhAproxModule,
    TSETunerStaticModule,
    TSETunerControllableModule,
    TSEVibratoStaticModule,
    TSEVibratoControllableModule,
    TSEVocoderStaticModule,
    TSEVocoderControllableModule,
    TSEVocoderAutomatableModule,
    TSESimpleVocoderStaticModule,
    TSESimpleVocoderControllableModule,
    TSESimpleVocoderAutomatableModule,
    TSEVoiceSynthStaticModule,
    TSEVoiceSynthControllableModule,
    TSEBufferedMp3PlayerModule,
    TSETransientProcessorStaticModule,
    TSETransientProcessorControllableModule,
    TSEModDelayStaticModule,
    TSELeslieStaticModule,
    TSELeslieControllableModule,
    TSELeslieAutomatedModule,
    TSEFrequencyShifterStaticModule,
    TSEFrequencyShifterControllableModule,
    TSEExciterModule,
    TSEExciterAutomatedModule,
    TSEDitherHighshelfNoiseshaperStaticModule,
    TSEDitherHighshelfNoiseshaperControllableModule,
    TSEDitherSharpNoiseshaperStaticModule,
    TSEDitherSharpNoiseshaperControllableModule,
    TSEAudioFileOscillatorModule,
    TSESimpleAudioFileOscillatorModule,
    TSEMp3PlayerModule,
    TSESimpleMp3PlayerModule,
    TSENoiseReductionStaticModule,
    TSENoiseReductionControllableModule,
    TLookaheadLimiterStaticSEModule,
    TLookaheadLimiterParamStaticSEModule,
    TLookaheadLimiterAutomatableSEModule);

function GetModuleProperties(Index: Integer; Properties: PSEModuleProperties): Boolean; cdecl; export;
begin
 if (Index >= 0) and (Index < Length(CModuleClasses)) then
  begin
   CModuleClasses[Index].GetModuleProperties(Properties);
   Result := True;
  end
 else Result := False;
end;

function MakeModule(Index: Integer; ProcessType: Integer; SEAudioMaster: TSE2AudioMasterCallback; Reserved: Pointer): Pointer; cdecl; export;
begin
 if (Index >= 0) and (Index < Length(CModuleClasses)) and (ProcessType = 1)
  then Result := CModuleClasses[Index].Create(SEAudioMaster, Reserved).Effect
  else Result := nil;
end;

exports 
  makeModule name 'makeModule',
  getModuleProperties name 'getModuleProperties';

end.